### PR TITLE
Upgrading superagent and lodash to latest versions.

### PR DESCRIPTION
**Pull request by tandrup**
## ✏️ Changes
  
Fixes a couple of vulnerabilies in older versions.
  
## 📷 Screenshots
 
N/A
  
## 🔗 References
  
N/A  
## 🎯 Testing
  
Not sure how you normally test stuff but `npm test` parses and it works in our Auth0 Log reader project.
  
## 🚀 Deployment
  
Shouldn't depend on anything.
  
## 🎡 Rollout
  
N/A
  
## 🔥 Rollback
  
N/A
  
### 📄 Procedure
  
N/A
 
## 🖥 Appliance
  
N/A

### CODE REVIEW

**Comment by fyockm** [comment]
@tandrup thanks for the PR. the `lodash` update should not cause any problems, but I'm concerned about the `superagent` change. has the API changed at all between `1.2.0` and `4.1.0`?

**Comment by tandrup** [comment]
@fyockm There's only a few API changes that relates to serverside JS (most changes are browser related). As far as I can tell it doesn't affect the code. They suggest migrating from `.end()` callbacks to `.then()` or `await`. But `.end()` still works in the current version. 
And then it now only supports Node 6 or later.

**Comment by zxan1285** [comment]
Tested this changes with some of logging-extensions - all is fine, but we don’t have `superagent@4.1.0` installed in webtask. Latest version available is `superagent@3.8.3`. It also works with 3.8.3.

**Comment by tandrup** [comment]
Hi @zxan1285 
I've downgraded to superagent 3.8.3 so we can at least get on that version. I'm not sure it will fix all the CVE's but it will at least reduce the number of CVE's.

**Comment by fyockm** [comment]
thanks @tandrup and @zxan1285 !

**Comment by tandrup** [comment]
@fyockm Do you know when this will be released?

**Pull request merged**
